---
# tasks file for django
# tasks file for common
- name: Install django centos
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install django for Debian 
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

